#! /bin/sh
### BEGIN INIT INFO
# Provides:          t238robottargeting
# Required-Start:    $all
# Required-Stop: 
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Run the t238-robot-targeting program
# Description:       Runs the t238-robot-targeting program via gradle.
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
JAVA_HOME=/usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/

case "$1" in
  start)
    cd /home/pi/Work/T238CameraTracking_pi/t238-robot-targeting-java/output && /usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/bin/java -Djava.library.path=/home/pi/Work/T238CameraTracking_pi/t238-robot-targeting-java/output -jar CameraVision-all.jar

	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  stop)
    cd /home/pi/Work/T238CameraTracking_pi/t238-robot-targeting-java && /home/pi/Work/T238CameraTracking_pi/t238-robot-targeting-java/gradlew stop
	;;
  status)
	# No-op
	exit $?
	;;
  *)
	echo "Usage: $0 start|stop" >&2
	exit 3
	;;
esac

:
